baseURL = "https://guerrasplace.netlify.app/"
title = "Guerra's Place"

languageCode = "en-us"
DefaultContentLanguage = "en"
paginate = 10

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

[params]
  author = "Gabriel Higginbotham"
  github = "https://github.com/higginbg"
  og_image = "/img/logos/logo-large.png"
  sitename = "Guerra's Place"

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 1
